
### Output configuration
#
# You can get the names of your outputs by running: swaymsg -t get_outputs

# office dock screen
# output DP-7 pos -170 -1411 res 1920x1200 scale 0.85
# To obtain the numbers (-170, -1411) the reasoning is the following:
#      The main display has a w=1920 and a h=1080. Since we scale the external monitor
#      by a factor of 0.85, it means that it will be 1/0.85 bigger, giving us the new
#      W = 1920 * (1/0.85) = 2258 and H = 1200 * (1.85) = 1411. Now, the vertical offset
#      is done (we have the external monitor directly on above the integrated one).
#      For the horizontal offset we want the two monitor aligned. So, some part of the
#      external monitor will "overflow" on the integrated one, and it will overflow
#      of exactly W - w = 338. Since we want them aligned in the center, this means 
#      that we will have (W-w)/2 pixel offset, giving us 169.411... ~ 170.
#      NEVERTHELESS, fractional scaling results in blurry shit.

##### Ultimate screen configuration
# integrated display
# Because of shit old version of sway on debian 11, we can't
# use negative coordinates. 
# To solve this problem, we put the main display at 1e3, 1e3, so we have 
# enough space to do any other screen. 
output eDP-1 pos 10000 10000 res 1920x1080 scale 1

## EXTRA (DIRECT) HDMI (for presentations and movies) - top of integrated
# This is a generic connection with external hdmi. Mainly for when doing presentations.
# The screen seats ABOVE the integrated.
output HDMI-A-1 pos 10000 8920 res 1920x1080

# disosiziOne nuova 
# output 'Samsung Electric Company SyncMaster HMBB405425' pos -1200 1080 res 1920x1200 scale 1 transform "270"
# output "Dell Inc. DELL P2317H HH77Y77JCKPB" pos 0 1400 res 1920x1080

# disosiziOne vecchia 
# Third screen horizontal
# output "Dell Inc. DELL P2317H HH77Y77JCKPB" pos 0 0 res 1920x1080 
# Third output vertical
output 'Samsung Electric Company SyncMaster HMBB405425' pos 720 0 res 1920x1200 scale 1 transform "270"
output "Dell Inc. DELL P2317H HH77Y77JCKPB" pos 1920 320 res 1920x1080

## WORK DISPLAYS
# dell display is 1920 pixel on the right and 550 pixel up
# output "Dell Inc. DELL P2317H HH77Y77JCKPB" pos 8080 9450 res 1920x1080 -- this is when the screen is up
# This is when the two screen are aligned
output "Dell Inc. DELL P2317H HH77Y77JCKPB" pos 8080 10000 res 1920x1080 
# The Samsung display is 1200 pixel on the left and 320 pixel up 
output 'Samsung Electric Company SyncMaster HMBB405425' pos 6880 9450 res 1920x1200 scale 1 transform "270"

## HOME DISPLAYS.
# direct hdmi home screen
# The first two are the interfaces connected when using the usb dock 
# The third one is added just in case the screen is conected viea HDMI-A-1.
output DP-2 pos 11920 10000 res 1920x1080
output DP-1 pos 11920 10000 res 1920x1080
output "Unknown 15B1 0000000000000" pos 11920 10000 res 1920x1080
