# System related
  # lock and suspend
  set $lock $HOME/.config/swaylock/swaylock-random-image.sh
  bindsym $mod+Shift+s exec systemctl suspend
  bindsym $alt+space exec $lock
  exec swayidle -w \
      timeout 300 '$lock -f' \
      timeout 600 'swaymsg "output * dpms off"' \
        resume 'swaymsg "output * dpms on"' \
      before-sleep '$lock -f'

    # Kill focused window
    bindsym $mod+Shift+q kill

    # Start your launcher
    bindsym $mod+d exec $menu

#
# Power keys 
#
      bindsym XF86PowerOff exec nwg-bar

# 
# Media keys:
#
      # bindsym XF86Display
      bindsym XF86MonBrightnessDown exec "python ~/.config/sway/scripts/brightness.py minus"
      bindsym XF86MonBrightnessUp exec "python ~/.config/sway/scripts/brightness.py plus"
      # bindsym XF86AudioMute exec pactl set-sink-mute @DEFAULT_SINK@ toggle
      # bindsym XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -5%
      # bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +5%
      bindsym XF86AudioMute exec "python ~/.config/sway/scripts/audio.py toggleMute 2>&1 > /tmp/audio_prova"
      bindsym XF86AudioLowerVolume exec "python ~/.config/sway/scripts/audio.py minus"
      bindsym XF86AudioRaiseVolume exec "python ~/.config/sway/scripts/audio.py plus"
      # bindsym XF86AudioMicMute
      # bindsym XF86RFKill
      bindsym Print exec grimshot --notify copy area
      bindsym Control+Print exec grimshot --notify save area

      bindsym XF86AudioPlay exec playerctl play-pause
      bindsym XF86AudioNext exec playerctl next
      bindsym XF86AudioPrev exec playerctl previous

# Convenience
  # Start a terminal
  bindsym $mod+Return exec $term
  # bindsym $alt+Control+t exec $term

  # Other application start bindings 
  bindsym $mod+t exec $HOME/.local/zen/zen
  bindsym $mod+s exec flatpak run org.zotero.Zotero 
  # Originally $mod+s is for stacking. I never use it...

  # Select audio sink 
  bindsym $mod+i exec $HOME/.local/scripts/audioselector.sh
  # select wifi network
  bindsym $mod+m exec $HOME/.local/scripts/networkselector.sh
  # play music/video
  bindsym $mod+Shift+u exec $HOME/.local/scripts/playVideo.sh
