fallback = ''
separator = ' '

[matching]
'discord' = ''
'balena-etcher' = ''
'Chia Blockchain' = ''
'Steam' = ''
'vlc' = ''
'org.qbittorrent.qBittorrent' = ''
'Thunderbird' = ''
'/thunderbird|Thunderbird/' = ''
# '/thunderbird|Thunderbird/' = '🐦'
'Postman' = ''
'Insomnia' = ''
'Bitwarden' = ''
'Google-chrome' = ''
'google-chrome' = ''
'Chromium' = ''
'Slack' = ''
# 'Code' = ''
'Code' = ''
# 'code-oss' = ''
# 'jetbrains-studio' = ''
'/Codium/' = ''

'Spotify' = ''
'GitHub Desktop' = ''

# Firefox Apps 
# '/(?i)Github.*Firefox/' = ''
'/(?i)Whatsapp.*Firefox/' = ''
'/(?i)firefox/' = ''
'/(?i)zen/' = ''
'Nightly' = ''

# Others
'/nvim ?\w*/' = ''
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''
'Alacritty' = ''
'kitty' = ''
'sioyek' = '🗎'
'evince' = '🗎'
# 'foot' = '👣'
'/zip/' = ''
'/md/' = ''
'/ranger/' = '🕶'
'/Zotero/' = '𝚭'
# '/Whatsapp/' = ''
