# exec sworkstyle &> /tmp/sworkstyle.log; swaynag -m "Executing sworkstyle"
# exec_always killall sworkstyle & exec ~/.config/sway/scripts/sworkstyle.sh
exec_always exec ~/.config/sway/scripts/sworkstyle.sh

