gaps inner 10

set $border 5

# remove border to the following apps 
for_window [app_id="kitty"] border pixel $border
for_window [class="zen"] border pixel $border
for_window [app_id="zen"] border pixel $border
for_window [app_id="mpv"] border pixel $border

for_window [title="Extension: (Bitwarden Password Manager).*"] floating enable

for_window [class="zoom" title="zoom"] floating enable
for_window [title="zoom" shell="xwayland"] floating enable 
for_window [class="zoom" shell="xwayland"] floating enable 
for_window [title="zoom"] floating enable 
